### Get me
GET http://localhost:3000/user/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsImVtYWlsIjoiZ2lvQHRlc3QuY29tIiwiaWF0IjoxNjY2NzkzNTI0LCJleHAiOjE2NjY3OTQ0MjR9.xXdfGLXpwJRutRJ6Huw369sc9XkXfNzZbHggSXDXkKg